POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzE4Y2JmOTQ1ODljM2MzMDg3MTFmNCIsInVzZXJuYW1lIjoianVhbiIsImlhdCI6MTY5MDQxNzMxMiwiZXhwIjoxNjkxMDIyMTEyfQ.AMS-Sr3Bnd6NDPcFeggC7YUf3Q5ENY-SYZVqOD-qbbo

{
  "content": "helloo",
  "important": true
}



